//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StageConfig.proto
namespace m
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StageConfig")]
  public partial class StageConfig : global::ProtoBuf.IExtensible
  {
    public StageConfig() {}
    
    private int _RankID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RankID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RankID
    {
      get { return _RankID; }
      set { _RankID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private float _ProtectPower;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ProtectPower", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ProtectPower
    {
      get { return _ProtectPower; }
      set { _ProtectPower = value; }
    }
    private float _ProtectRotateSpeed;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ProtectRotateSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ProtectRotateSpeed
    {
      get { return _ProtectRotateSpeed; }
      set { _ProtectRotateSpeed = value; }
    }
    private float _ProtectRotateInnerSpeed;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ProtectRotateInnerSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ProtectRotateInnerSpeed
    {
      get { return _ProtectRotateInnerSpeed; }
      set { _ProtectRotateInnerSpeed = value; }
    }
    private float _JGBRotateSpeed;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"JGBRotateSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float JGBRotateSpeed
    {
      get { return _JGBRotateSpeed; }
      set { _JGBRotateSpeed = value; }
    }
    private float _JGBPower;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"JGBPower", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float JGBPower
    {
      get { return _JGBPower; }
      set { _JGBPower = value; }
    }
    private string _TemplateList;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"TemplateList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TemplateList
    {
      get { return _TemplateList; }
      set { _TemplateList = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}