//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protoFile/test.proto
namespace chanyu
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RulesIdProto")]
  public partial class RulesIdProto : global::ProtoBuf.IExtensible
  {
    public RulesIdProto() {}
    
    private int _rule;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rule
    {
      get { return _rule; }
      set { _rule = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _talentIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"talentIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> talentIds
    {
      get { return _talentIds; }
    }
  

    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _ownedTalentIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"ownedTalentIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> ownedTalentIds
    {
      get { return _ownedTalentIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}