//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StageConfig.proto
namespace m
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StageConfig")]
  public partial class StageConfig : global::ProtoBuf.IExtensible
  {
    public StageConfig() {}
    
    private int _RankID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RankID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RankID
    {
      get { return _RankID; }
      set { _RankID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _TemplateList;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"TemplateList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TemplateList
    {
      get { return _TemplateList; }
      set { _TemplateList = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}